---
title: "Preparing for Training"
author: "Kate Miller"
date: "9/25/2020"
output: html_document
---
<h2>Installing required software</h2>
The only thing you really need to do to prepare for R training is to install the latest version of R and RStudio. We'll talk about the difference between R and RStudio on the first day, but for now, just make sure they're installed. Directions for installing R/RStudio are below. If you run into any problems, check the instructions at R for Data Science <a href="https://r4ds.had.co.nz/introduction.html#prerequisites">Section 1.4.1 and 1.4.2</a>. 

<b style="color:red">NOTE: If you don't have Administrative privileges on your computer, you will have to submit an <a href="https://npshelpdesk.nps.gov/">IT HelpDesk Ticket</a> (need to be on VPN or NPS network to access this link) to install R and RStudio, which could take a while. PLEASE PLAN AHEAD!</b>  

Even if you already have R or RStudio installed, please install the latest versions of both programs. R recently went through a major version change from 3.x to 4.x with some potential code-breaking changes. The latest versions are needed to ensure everyone's code behaves the same way. 
<br>

<details open><summary class='drop'>Install the latest version of R (4.1.2 as of January 2022)</summary>
Assuming you're on a PC, the installer for the latest version of R can be downloaded from <a href="https://cran.r-project.org/bin/windows/base/">The Comprehensive R Archive Network (CRAN)</a>. You'll want to download the R installer by clicking on "Download R 4.0.4 for Windows", or whatever the latest version number happens to be. After it downloads, open and run the installer with default settings. Note that there's no need to pin R to your taskbar or add a shortcut to your desktop. For 99% of your needs, you'll run R within RStudio, and won't ever open R directly.
</details>
<br>

<details open><summary class='drop'>Install RStudio</summary>
The installer for RStudio for PCs can be downloaded <a href="https://rstudio.com/products/rstudio/download/#download">here</a>. You'll need to click on the large blue "DOWNLOAD RSTUDIO FOR WINDOWS" button to download the installer. After it downloads, open and run the installer with default settings. I like having RStudio pinned to my taskbar, so it's easier to find/open, but it's up to you and your preferences.
</details>
<br>

<details open><summary class='drop'>Optional Reading</summary>
We know you're all busy and have to prioritize how you spend your time. If you have any time before training starts, we highly recommend reading <a href="https://stat545.com/r-basics.html">Chapter 2: R basics and workflows</a> in STAT545. This is an online book based on a graduate level statistics class that Dr. Jenny Bryan teaches and is turning into this book. She's a stats professor turned senior programmer at RStudio, and I really like how she approaches programming R in this book. 
</details>
<br>

<details open><summary class='drop'>Structure of training</summary>
The training will take place over 4 half days. Each day will run from 10-2 MST via MS Teams. The hour before training, and the hour after training will also be posted by at least one trainer as office hours, in case there are questions that couldn't be handled during training. 

Each training session has three trainers assigned, two of which will be the main instructors. The third trainer will manage the chat. For most of the training, one of the trainers will share their screen to walk through the website and then demo with live coding. It will help a lot if you have 2 monitors, so you can have the screen being shared on one monitor and your own session of RStudio open on the other.   

Four days is barely enough to scratch the surface on what you can do in R. Our goals with this training are to help you get beyond the initial learning curve that can be really challenging to climb on your own, and to expose you to some of the really useful things R can do for you in your work. The trainers put lot of thought and time into designing this training. We did it because we enjoy coding in R and it has greatly increased efficiency and productivity in our jobs. We hope you have a similar experience as you start out on this R learning curve. As you learn more, please share your skills and code with others to help us build a larger community of R users in IMD who can learn from each other. 

Finally, to help us improve this training for future sessions, please leave feedback in the <a href="https://forms.office.com/Pages/ResponsePage.aspx?id=urWTBhhLe02TQfMvQApUlFh5GkMREZNMjYcWk1MpLQ9UNVdDUlUzT0FZSlBMS0dLNkRGQklGQjlHNS4u">training feedback form</a>.  

</details>
<hr>

